# Generated by Django 2.0.1 on 2018-05-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchase',
            field=models.IntegerField(),
        ),
    ]
